### ISSUE TITLE
wrong status code for updating

### ISSUE THREAD

**Issue by zachmann** [indigo-dc/CDMI#10]
updating a dataobject/container/domain should return a Http Statuscode of 204

REQ-> curl -v -X PUT http://localhost:8080/object2 -H "Content-Type:application/cdmi-object" -d '{value:"this is a test", domainURI:"/cdmi_domains/test", metadata:{updated:"by test"}}'

RES->201 Created

**Comment by bertl4398** [comment]
outdated
