### ISSUE TITLE
NPE on getting the capability of a file 

### ISSUE THREAD

**Issue by anupash** [indigo-dc/CDMI#102]
**On master**

**Steps to reproduce:**
 http GET 'https://dcache-qos-01.desy.de:8443/random.img?capabilitiesURI;metadata' X-CDMI-Specification-Version:1.1 Authorization:'Bearer #OIDC' Accept:application/cdmi-object --print=HhBb

**StackTrace:**
https://gist.github.com/anupash/c4baf41063f3c09cf13d94e228c68239

**Comment by bertl4398** [comment]
should work again now
