### ISSUE TITLE
updating specific fields of dataobject doesn't work

### ISSUE THREAD

**Issue by zachmann** [indigo-dc/CDMI#11]
updating specific fields of a dataobject doesn't work

REQ-> curl -v -X PUT http://localhost:8080/object -H "Content-Type:application/cdmi-object" -d '{value:"new", metadata:{new:"by test"}}'
RES-> created

REQ-> curl -v -X PUT http://localhost:8080/object?metadata:update -H "Content-Type:application/cdmi-object" -d '{metadata:{update:"by test"}}'

RES-> 406 Not Acceptable

**Comment by zachmann** [comment]
if the value-field is present, the response isn't a status of 406
but all fields a updated and not only the specified

**Comment by bertl4398** [comment]
outdated
