### ISSUE TITLE
root container via object id not found

### ISSUE THREAD

**Issue by bertl4398** [indigo-dc/CDMI#2]
root container can not be found via object id

e.g.

REQ -> curl -v localhost:8080
RES -> {"objectID":"000000080018127D61363434346263612D313530662D3434"}

REQ -> curl -v localhost:8080/cdmi_objectid/000000080018127D61363434346263612D313530662D3434

RES -> not found

**Comment by zachmann** [comment]
root container and objectid-file for rootContainer with more information are created by startup.
so root container can be found by objectid.
root container information can be specified in containerDaoImpl.createRootContainer()
