### ISSUE TITLE
Incorrect response when Unauthorised expected

### ISSUE THREAD

**Issue by anupash** [indigo-dc/CDMI#33]
On Performing the following request,

curl http://<qos-server>:8080/testcontainer

{"timestamp":1467279042812,"status":400,"error":"Bad Request","exception":"org.springframework.web.bind.ServletRequestBindingException","message":"Missing request header 'Authorization' for method parameter of type String","path":"/testcontainer"}

Http Response "401: Unauthorized" expected.

**Comment by bertl4398** [comment]
it is a bad request since the authorization header is missing

unauthorized is returned on wrong authorization credentials

**Comment by anupash** [comment]
As per www standards : http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

> 400 Bad Request
> 
> The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modifications.

As per the CDMI document Section [5.12.3]:

> 5.12.3 Client authentication
> A CDMI client shall comply with all security requirements for HTTP that apply to clients. CDMI clients can be responsible for initiating user authentication for each CDMI operation that is performed. The CDMI server functions as the authenticator and receives and validates authentication credentials from the client.
> 
> RFC 2616 and RFC 2617 define requirements for HTTP authentication, which generally starts with an HTTP client request. If the client request does not include an "Authorization" header and authentication is required, the server responds with an HTTP status code of 401 Unauthorized and a WWW-Authenticate response header. The HTTP client shall then respond with the appropriate Authorisation header in a subsequent request.
