### ISSUE TITLE
binary files in git

### ISSUE THREAD

**Issue by paulmillar** [indigo-dc/CDMI#34]
Binary packages (such as cdmi-server-1.0-1.el7.centos.x86_64.rpm) are present in the git repo.

Please remove them!

**Comment by bertl4398** [comment]
will be done when we have a place to host the packages

**Comment by paulmillar** [comment]
Storing binary files in git is wrong independent of whether there is a repo for these files.

Copy them into an Apache server (e.g., http://cdmi-qos.data.kit.edu/) if there's nothing better, but don't leave them here and certainly don't update them.
