### ISSUE TITLE
Changing capability on a data object without querying for its capabilities first returns some JSON (possibly incorrect behavior)

### ISSUE THREAD

**Issue by anupash** [indigo-dc/CDMI#54]
$ http -a restadmin:restadmin PUT http://dcache-qos-01:8080/cryptohardeningbook.pdf  capabilitiesURI="/cdmi_capabilities/dataobject/disk+tape" X-CDMI-Specification-Version:1.1 Content-Type:application/cdmi-object --print=HhBb

```
PUT /cryptohardeningbook.pdf HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Authorization: Basic cmVzdGFkbWluOnJlc3RhZG1pbg==
Connection: keep-alive
Content-Length: 62
Content-Type: application/cdmi-object
Host: dcache-qos-01:8080
User-Agent: HTTPie/0.9.4
X-CDMI-Specification-Version: 1.1

{"capabilitiesURI": "/cdmi_capabilities/dataobject/disk+tape"}

HTTP/1.1 201 Created
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Disposition: inline;filename=f.txt
Content-Length: 379
Content-Type: application/cdmi-object;charset=UTF-8
Date: Mon, 01 Aug 2016 13:45:09 GMT
Expires: 0
Pragma: no-cache
Server: Apache-Coyote/1.1
Set-Cookie: JSESSIONID=DB50955D95CBF1DF3D2BD08F952BC76E; Path=/; HttpOnly
X-CDMI-Specification-Version: 1.1.1
X-Content-Type-Options: no sniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block

{"metadata":{},"parentURI":"/","capabilitiesURI":"/cdmi_capabilities/dataobject","objectName":"cryptohardeningbook.pdf","mimetype":"application/octet-stream","completionStatus":"Complete","objectID":"0001869F00181FC830383334653565392D636232352D3461","parentID":"0001869F00184DF362623036356661362D303132382D3434","domainURI":"/cdmi_domains","objectType":"application/cdmi-object"}

```

See full logs here,
[https://gist.github.com/anupash/21ba3910480f3c8ffcac38fdcedf83b5](https://gist.github.com/anupash/21ba3910480f3c8ffcac38fdcedf83b5)

**Comment by bertl4398** [comment]
dont see a problem here

**Comment by anupash** [comment]
If you read your documentation of the QoS API (https://docs.google.com/document/d/1V2MjSM1zkqM07qmRvUFcZ8BBPz1lUayylN7YLG8Ku4U/edit#), the PUT request to modify the cdmi_capability of an object does not return a response with JSON. 

This worked fine when you query for the capability of an object first and then modify it. But, if you try to modify the capability without querying for it you should not suddenly receive a JSON in the response. This is the wrong behaviour I was trying to point.

**Comment by paulmillar** [comment]
This does seems to be a violation of the QoS spec.

**Comment by bertl4398** [comment]
should be fixed
