### ISSUE TITLE
[redis-integration] Changing the capability of the object does not work

### ISSUE THREAD

**Issue by anupash** [indigo-dc/CDMI#61]
1. GET https://dcache-qos-01:8443/random.img?capabilitiesURI;metadata

> {"metadata":{"cdmi_data_redundancy_provided":"1","cdmi_geographic_placement_provided":"[ \"DE\"]","cdmi_latency_provided":"600000"},"capabilitiesURI":"/cdmi_capabilities/dataobject/tape"}
1. GET https://dcache-qos-01:8443/random.img?capabilitiesURI;metadata

> {"metadata":{"cdmi_data_redundancy_provided":"1","cdmi_geographic_placement_provided":"[ \"DE\"]","cdmi_latency_provided":"600000"},"capabilitiesURI":"/cdmi_capabilities/dataobject/tape"}
1. PUT https://dcache-qos-01:8443/random.img 

>  {"capabilitiesURI": "/cdmi_capabilities/dataobject/disk+tape"}
1. GET https://dcache-qos-01:8443/random.img?capabilitiesURI;metadata

> {"metadata":{"cdmi_data_redundancy_provided":"1","cdmi_geographic_placement_provided":"[ \"DE\"]","cdmi_latency_provided":"600000"},"capabilitiesURI":"/cdmi_capabilities/dataobject/tape"}

Logs attached

https://gist.github.com/anupash/de42976dc1a2a520e8abc6319dcbaf4e

**Comment by bertl4398** [comment]
changing the capability URI is implemented in the specific storage back-end module and not the CDMI server .. your log indicates that there is probably an issue within your dCacheStorageBackend module e.g. "in transition to null"

2016-09-07 12:19:43 INFO o.d.s.dCacheStorageBackend:126 - Cdmi Capability of object /random.img is /cdmi_capabilities/dataobject/tape; in transition to null

if this is also an issue with the built-in dummy_filesystem module for you feel free to reopen

**Comment by anupash** [comment]
As per the cdmi-spi documentation, 

> - @param targetCapabilitiesUri the target capabilitiesUri (reference to set of QoS attributes),
>   -        if a transition from the current capabilitiesUri to the target capabilitiesUri has been
>   -        requested if no transition has been requested the value should be null.
>     */
> 
> in transition to null 
> "null" here means that the targetCapabiliuesUri field in the constructor of CdmiObjectStatus is set to null, which is perfectly valid. 

More over,  if you had looked at the these two line carefully, 

> 2016-09-07 12:19:34  INFO o.d.s.dCacheStorageBackend:86 - QoS Update of /random.img to /cdmi_capabilities/dataobject/disk+tape: Transition was successful
> 
> 2016-09-07 12:19:34 DEBUG e.k.s.c.d.r.CdmiObjectDaoImpl:98 - set objectid:0001869F0018AE2D64623966613539322D623537322D3461 {"metadata":{},"parentURI":"/","capabilitiesURI":"/cdmi_capabilities/dataobject/disk+tape","objectName":"random.img","mimetype":"application/octet-stream","completionStatus":"Complete","objectID":"0001869F0018AE2D64623966613539322D623537322D3461","parentID":"0001869F0018CC9231373039313239352D323035622D3435","domainURI":"/cdmi_domains","objectType":"application/cdmi-object"}

you would have seen that the QoS update as far as dCacheStorageBackend is concerned is successful. Therefore, you see the "CdmiObjectDaoImpl:98 - set ..". You can see clearly that the capabilitiesURI to be /cdmi_capabilities/dataobject/disk+tape

But when I query it back, I still get the old capability of the file.

**Comment by bertl4398** [comment]
as mentioned above ..

> if this is also an issue with the built-in dummy_filesystem module for you feel free to reopen

otherwise there is nothing i can do here, the built-in dummy_filesystem module works for me as does the hpss backend module
