### ISSUE TITLE
attempt to delete nonexisting container works

### ISSUE THREAD

**Issue by zachmann** [indigo-dc/CDMI#7]
attempt to delete a container that doesn't exist, does not respon in a Httpstatus of 404 Not Found

REQ -> curl -v -X DELETE http://localhost:8080/doesntexist -H "Content-Type:application/cdmi-container" -d '{}'

RES -> 204 No Content

Don't know if it really matters

**Comment by zachmann** [comment]
same for dataobjects

**Comment by bertl4398** [comment]
outdated
